# Generated by Django 5.2.1 on 2025-06-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdsrecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
