# Generated by Django 5.2.1 on 2025-06-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0002_alter_sdsrecord_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdsrecord',
            name='cas_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='uploaded_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
