# Generated by Django 5.2.1 on 2025-06-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0003_alter_sdsrecord_cas_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdsrecord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdsrecord',
            name='application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdsrecord',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdsrecord',
            name='hazard_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='cas_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdsrecord',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
